# Generated by Django 5.1.4 on 2024-12-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartechchar',
            options={'verbose_name': 'Технические характеристики', 'verbose_name_plural': 'Технические характеристики'},
        ),
    ]
