# Generated by Django 5.1.4 on 2024-12-27 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartechchar',
            options={'verbose_name': 'Технические характеристики', 'verbose_name_plural': 'Технические характеристики'},
        ),
        migrations.AlterField(
            model_name='cartechchar',
            name='car_milage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(600000)]),
        ),
        migrations.AlterField(
            model_name='cartechchar',
            name='power',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='cartechchar',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1800)]),
        ),
    ]
